---
- hosts: webservers
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install prerequisites
      apt: update_cache=yes state=absent force_apt_get=yes cache_valid_time=3600
      tags: [ system ]

    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=no state=absent cache_valid_time=3600
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      tags: [ system ]

    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=absent cache_valid_time=3600
      loop: "{{ php_modules }}"
      tags: [ system ]

    - name: Remvoe mysql 
      shell: |
        systemctl stop mysql
        sudo apt purge mysql-server* -y
        sudo rm -r /etc/mysql /var/lib/mysql
        sudo rm -r /var/log/mysql
        sudo apt autoremove -y

